### ISSUE TITLE
Add new level to logger

### ISSUE THREAD

**Issue by kgevorkyan** [diktat-static-analysis/save#184]
For now we have 4 levels: `[INFO]` `[DEBUG]` `[WARN]` `[ERROR]`, however now it's a lot of debug information, which could be useful only in rare cases, but generally it just loads output. E.g.: execution output of `ProcessBuilder`

It's suggested to create new additional level `[TRACE]` for such things

**Comment by akuleshov7** [comment]
We also have --quite mode

**Comment by kgevorkyan** [comment]
Decided after discussion: We would support both features: 
1) `--quite` mode should hide all warnings
2) Support new level `[TRACE]`, which will be used to some low level information
