### ISSUE TITLE
Performance: save-cli is extremely slow with long `testFiles` parameter

### ISSUE THREAD

**Issue by petertrr** [diktat-static-analysis/save#339]
When repo with tests has a lot of tests and test suites (~40k) and `testFiles` is long (even about 10), save-cli takes huge time to start operating. For `testFiles.size == 5` it takes about 90 seconds to start processing first real save.toml

**Comment by kgevorkyan** [comment]
Also, can we have some problems because of limitation (if any) of command size during of execution by `sh -c`, or cmd /c`?
Does these shells have some limits?

**Comment by petertrr** [comment]
> Does these shells have some limits?

I believe, only cmd has limits? `sh` should be able to handle almost anything

**Comment by petertrr** [comment]
Some findings:
* We should filter included/excluded test suites *before* checking if plugins have resources
* Merging of configs takes a long time with batch of 25 `testFiles`
